"""document_visibility

Revision ID: 9d4c4a71c3aa
Revises: e4f21df34453
Create Date: 2026-06-12 15:03:42.023726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4c4a71c3aa'
down_revision: Union[str, Sequence[str], None] = 'e4f21df34453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('visibility', sa.String(length=20), server_default='department', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'visibility')
    # ### end Alembic commands ###
