"""intelligence fields: document_type, word_count

Revision ID: e4f21df34453
Revises: 422a00f8181c
Create Date: 2026-06-11 10:54:31.600514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f21df34453'
down_revision: Union[str, Sequence[str], None] = '422a00f8181c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
