/**
 * Export a chat conversation to PDF via the browser's native print-to-PDF.
 *
 * Why not jsPDF/html2canvas: this is text-heavy content where the browser's own
 * print engine produces cleaner, selectable, reflowable output with zero new
 * dependencies and works in every browser. We open a print-optimized window and
 * call window.print(); the user picks "Save as PDF" as the destination.
 */

"use client";

import type { MessageSource } from "@/types";

// Loose shapes so both the chat page's local UIMessage and the API's ChatMessage
// satisfy the contract — all we need to render is role + content + sources.
interface ExportableMessage {
  role: string;
  content: string;
  sources?: MessageSource[] | null;
}
interface ExportableSession {
  title: string | null;
}

/** Escape the four HTML-significant characters so message text can't break (or
 *  inject into) the generated document. Line breaks are preserved via CSS
 *  (white-space: pre-wrap), so no <br> substitution is needed. */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** "Source: Filename.pdf, page 4" (page omitted when null, e.g. DOCX). */
function formatSource(s: MessageSource): string {
  const page = s.page != null ? `, page ${s.page}` : "";
  return `Source: ${escapeHtml(s.filename)}${page}`;
}

function renderMessage(m: ExportableMessage): string {
  const isUser = m.role === "user";
  const label = isUser ? "You:" : "Pragya:";
  const sources =
    !isUser && m.sources && m.sources.length > 0
      ? `<div class="sources">${m.sources.map(formatSource).join("<br>")}</div>`
      : "";
  return `
    <div class="msg ${isUser ? "user" : "assistant"}">
      <div class="label">${label}</div>
      <div class="content">${escapeHtml(m.content)}</div>
      ${sources}
    </div>`;
}

function buildDocument(session: ExportableSession, messages: ExportableMessage[]): string {
  const title = session.title ?? "Conversation";
  const exportDate = new Date().toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const body = messages.map(renderMessage).join("");

  // Inline styles: Georgia serif for headings, system-ui for body, black on white.
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(title)} — Pragya</title>
<style>
  * { box-sizing: border-box; }
  body {
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
    color: #000; background: #fff; margin: 24px; line-height: 1.6;
  }
  .wordmark { font-family: Georgia, "Times New Roman", serif; font-size: 18px; }
  .title { font-family: Georgia, "Times New Roman", serif; font-size: 16px; margin-top: 4px; }
  .date {
    font-family: "JetBrains Mono", ui-monospace, monospace;
    font-size: 11px; color: #555; margin-top: 2px;
  }
  hr { border: none; border-top: 1px solid #ccc; margin: 16px 0; }
  .msg { margin: 14px 0; page-break-inside: avoid; }
  .msg .label {
    font-family: "JetBrains Mono", ui-monospace, monospace;
    font-size: 10px; color: #666; text-transform: uppercase;
    letter-spacing: 0.08em; margin-bottom: 3px;
  }
  .user { text-align: right; }
  .assistant { text-align: left; }
  .content { white-space: pre-wrap; font-size: 13px; }
  .sources {
    margin-top: 6px;
    font-family: "JetBrains Mono", ui-monospace, monospace;
    font-size: 10px; color: #555;
  }
  .footer {
    margin-top: 28px; border-top: 1px solid #ccc; padding-top: 8px;
    font-family: "JetBrains Mono", ui-monospace, monospace;
    font-size: 10px; color: #777;
  }
  @media print { body { margin: 2cm; } }
</style>
</head>
<body>
  <div class="wordmark">Pragya</div>
  <div class="title">${escapeHtml(title)}</div>
  <div class="date">Exported ${escapeHtml(exportDate)}</div>
  <hr>
  ${body || '<p class="content">This conversation has no messages.</p>'}
  <div class="footer">Generated by Pragya · ${escapeHtml(exportDate)}</div>
</body>
</html>`;
}

/**
 * Open a print-optimized window for the conversation and trigger the print
 * dialog. Must be called from a user gesture (a click) or the pop-up is blocked.
 */
export function exportChatAsPDF(
  session: ExportableSession,
  messages: ExportableMessage[]
): void {
  const win = window.open("", "_blank", "width=820,height=900");
  if (!win) {
    // Pop-up blocked — surface a hint rather than failing silently.
    alert("Please allow pop-ups for this site to export the chat as PDF.");
    return;
  }
  win.document.open();
  win.document.write(buildDocument(session, messages));
  win.document.close();
  win.focus();
  // Give the new document a moment to lay out (fonts, reflow) before printing.
  // document.write content doesn't reliably fire onload, so a short delay is the
  // robust cross-browser choice.
  setTimeout(() => win.print(), 350);
}
